// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"es_test/Service"
	"es_test/common"
	"es_test/conf"
	"es_test/dao"
	"es_test/handler"
)

// Injectors from wire.go:

func InitializeHandler(conf *conf.Config) *handler.UserHandler {
	engine := common.NewRouterClient()
	client := common.NewEsClient(conf)
	userES := dao.NewUserES(client, conf)
	userService := Service.NewUserService(userES)
	userHandler := handler.NewUserHandler(engine, userService)
	return userHandler
}
